### ISSUE TITLE
MESA software running on single AMESD computer running slow

### ISSUE THREAD

**Issue by riaanvddool** [MESASADC/mesawildfire#2]
Do we need to move Postgresql and/or Geoserver to the Windows PC?

**Comment by taxmanyana** [comment]
Great suggestion. We can move the Database to Windows, this will definitely improve performance. How complicated is this to achieve? and how soon?

**Comment by riaanvddool** [comment]
I think we can defer this option now that the FDI queries have been optimized for performance.
